[lattice]
type = "square lattice"
L = 2
W = 2
virtual_dim = 2
initial = "ferro"
noise = 0.0

[model]
type = "spin"
Jz = -1.0
Jx = 0.0
Jy = 0.0
G = 2.8

[parameter.general]
is_real = true
output = "output_28"
tensor_save = "output_wf_28"
tensor_load = "output_wf_27"

[parameter.simple_update]
num_step = 1000
tau = 0.01

[parameter.full_update]
num_step = 0
tau = 0.01

[parameter.ctm]
iteration_max = 100
dimension = 10
